title: plattsoft.net
author: Plattsoft Solutions, LLC
email: adam@plattsoft.net

description: ""

domain: plattsoft.net
url: https://plattsoft.net
baseurl: /

twitter_username: platta
github_username:  platta
linkedin_username: platta

# Google analytics key.
google_analytics: UA-17483215-1

# Build settings
markdown: kramdown

plugins:

sass:
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
